name: Deploy Eustia

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: project/eustia-docs
    - uses: actions/setup-node@v4
      with:
        node-version: '10.x'
    - working-directory: ./project/eustia-docs
      run: |
        npm i
        npm run build
        mkdir -p ../../liriliri/eustia
        cp -r dist/* ../../liriliri/eustia
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "liriliri/eustia/"
        target: "/var/www/"    
    